import type { Metadata } from "next"; 
import { Inter } from "next/font/google";
import "./globals.css";
import TopHeader from "@/components/TopHeader";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import LogosSection from "@/components/LogosSection";
import { CartProvider } from "@/app/context/CartContext"; // Import CartProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Ecommerce Store",
  description: "Generated by Mirza Mohsin Baig",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative">
        <CartProvider> {/* Wrap everything inside CartProvider */}
          <TopHeader />
          <Header />
          {children}
          <LogosSection />
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
